[project]
name = "cryptography"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "NoSignificantWorries", email = "dmitry.karpachev@hotmail.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
cryptography = "cryptography:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
